version: "3.8"

services:

  mysqldb:
    image: mysql:5.7
    container_name: MYSQL_DB
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=baskartest
    ports:
      - 3307:3306
  app:
    build:
      context: .
    restart: on-failure
    ports:
      - 8084:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://MYSQL_DB:3306/baskartest
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysqldb